# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
create_project -in_memory -part xcvu11p-flga2577-3-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/XILINX_PROJECTS/INTLVD-EDWARDS-ECC-R08/INTLVD-EDWARDS-ECC-R08.cache/wt [current_project]
set_property parent.project_path D:/XILINX_PROJECTS/INTLVD-EDWARDS-ECC-R08/INTLVD-EDWARDS-ECC-R08.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/XILINX_PROJECTS/INTLVD-EDWARDS-ECC-R08/INTLVD-EDWARDS-ECC-R08.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/XILINX_PROJECTS/INT-EDWARDS-ECC/INT-EDWARDS-ECC.srcs/sources_1/new/CSA.vhd
  D:/XILINX_PROJECTS/INTLVD-EDWARDS-ECC-R08/INTLVD-EDWARDS-ECC-R08.srcs/sources_1/new/CURVE_PACK.vhd
  D:/XILINX_PROJECTS/INTLVD-EDWARDS-ECC-R08/INTLVD-EDWARDS-ECC-R08.srcs/sources_1/new/EDPA.vhd
  D:/XILINX_PROJECTS/INTLVD-EDWARDS-ECC-R08/INTLVD-EDWARDS-ECC-R08.srcs/sources_1/new/EDPD.vhd
  D:/XILINX_PROJECTS/INT-EDWARDS-ECC/INT-EDWARDS-ECC.srcs/sources_1/new/INTLVD_RED.vhd
  D:/XILINX_PROJECTS/INT-EDWARDS-ECC/INT-EDWARDS-ECC.srcs/sources_1/new/LUT_P.vhd
  D:/XILINX_PROJECTS/INT-EDWARDS-ECC/INT-EDWARDS-ECC.srcs/sources_1/new/LUT_Y.vhd
  D:/XILINX_PROJECTS/INTLVD-EDWARDS-ECC-R08/INTLVD-EDWARDS-ECC-R08.srcs/sources_1/new/MADD.vhd
  D:/XILINX_PROJECTS/INTLVD-EDWARDS-ECC-R08/INTLVD-EDWARDS-ECC-R08.srcs/sources_1/new/MSUB.vhd
  D:/XILINX_PROJECTS/INT-EDWARDS-ECC/INT-EDWARDS-ECC.srcs/sources_1/new/REDUCER.vhd
  D:/XILINX_PROJECTS/INT-EDWARDS-ECC/INT-EDWARDS-ECC.srcs/sources_1/new/REGCSA.vhd
  D:/XILINX_PROJECTS/INT-EDWARDS-ECC/INT-EDWARDS-ECC.srcs/sources_1/new/SELUNIT.vhd
  D:/XILINX_PROJECTS/INT-EDWARDS-ECC/INT-EDWARDS-ECC.srcs/sources_1/new/SHMOD.vhd
  D:/XILINX_PROJECTS/INTLVD-EDWARDS-ECC-R08/INTLVD-EDWARDS-ECC-R08.srcs/sources_1/new/EDECC.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/XILINX_PROJECTS/INTLVD-EDWARDS-ECC-R08/INTLVD-EDWARDS-ECC-R08.srcs/constrs_1/new/Timing.xdc
set_property used_in_implementation false [get_files D:/XILINX_PROJECTS/INTLVD-EDWARDS-ECC-R08/INTLVD-EDWARDS-ECC-R08.srcs/constrs_1/new/Timing.xdc]


synth_design -top EDECC -part xcvu11p-flga2577-3-e -directive RuntimeOptimized -retiming -resource_sharing on -control_set_opt_threshold 1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef EDECC.dcp
create_report "synth_3_synth_report_utilization_0" "report_utilization -file EDECC_utilization_synth.rpt -pb EDECC_utilization_synth.pb"
